/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface BattleShipInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createGame"
      | "finalizeGame"
      | "games"
      | "getBoards"
      | "getGame"
      | "operator"
      | "presidentsSelected"
      | "shipsPlaced"
      | "shotFired"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GameCreated"
      | "GameFinalized"
      | "PresidentsSelected"
      | "ShipsPlaced"
      | "ShotFired"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createGame",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeGame",
    values: [BytesLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "games", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getBoards",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getGame", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "operator", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "presidentsSelected",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "shipsPlaced",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "shotFired",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "createGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeGame",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "games", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBoards", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "operator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "presidentsSelected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shipsPlaced",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "shotFired", data: BytesLike): Result;
}

export namespace GameCreatedEvent {
  export type InputTuple = [gameId: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [gameId: string, timestamp: bigint];
  export interface OutputObject {
    gameId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameFinalizedEvent {
  export type InputTuple = [
    gameId: BytesLike,
    winner: BigNumberish,
    board1: BytesLike,
    board2: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    gameId: string,
    winner: bigint,
    board1: string,
    board2: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    gameId: string;
    winner: bigint;
    board1: string;
    board2: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PresidentsSelectedEvent {
  export type InputTuple = [
    gameId: BytesLike,
    p1President: BigNumberish,
    p2President: BigNumberish
  ];
  export type OutputTuple = [
    gameId: string,
    p1President: bigint,
    p2President: bigint
  ];
  export interface OutputObject {
    gameId: string;
    p1President: bigint;
    p2President: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ShipsPlacedEvent {
  export type InputTuple = [gameId: BytesLike, playerNum: BigNumberish];
  export type OutputTuple = [gameId: string, playerNum: bigint];
  export interface OutputObject {
    gameId: string;
    playerNum: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ShotFiredEvent {
  export type InputTuple = [
    gameId: BytesLike,
    playerNum: BigNumberish,
    row: BigNumberish,
    col: BigNumberish,
    result: BigNumberish
  ];
  export type OutputTuple = [
    gameId: string,
    playerNum: bigint,
    row: bigint,
    col: bigint,
    result: bigint
  ];
  export interface OutputObject {
    gameId: string;
    playerNum: bigint;
    row: bigint;
    col: bigint;
    result: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BattleShip extends BaseContract {
  connect(runner?: ContractRunner | null): BattleShip;
  waitForDeployment(): Promise<this>;

  interface: BattleShipInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createGame: TypedContractMethod<[gameId: BytesLike], [void], "nonpayable">;

  finalizeGame: TypedContractMethod<
    [
      gameId: BytesLike,
      winner: BigNumberish,
      board1: BytesLike,
      board2: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  games: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, bigint, string, string, bigint, bigint] & {
        phase: bigint;
        winner: bigint;
        p1President: bigint;
        p2President: bigint;
        board1: string;
        board2: string;
        createdAt: bigint;
        finalizedAt: bigint;
      }
    ],
    "view"
  >;

  getBoards: TypedContractMethod<
    [gameId: BytesLike],
    [[string, string] & { board1: string; board2: string }],
    "view"
  >;

  getGame: TypedContractMethod<
    [gameId: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        phase: bigint;
        winner: bigint;
        p1President: bigint;
        p2President: bigint;
        createdAt: bigint;
        finalizedAt: bigint;
      }
    ],
    "view"
  >;

  operator: TypedContractMethod<[], [string], "view">;

  presidentsSelected: TypedContractMethod<
    [gameId: BytesLike, p1President: BigNumberish, p2President: BigNumberish],
    [void],
    "nonpayable"
  >;

  shipsPlaced: TypedContractMethod<
    [gameId: BytesLike, playerNum: BigNumberish],
    [void],
    "nonpayable"
  >;

  shotFired: TypedContractMethod<
    [
      gameId: BytesLike,
      playerNum: BigNumberish,
      row: BigNumberish,
      col: BigNumberish,
      result: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createGame"
  ): TypedContractMethod<[gameId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeGame"
  ): TypedContractMethod<
    [
      gameId: BytesLike,
      winner: BigNumberish,
      board1: BytesLike,
      board2: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "games"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, bigint, string, string, bigint, bigint] & {
        phase: bigint;
        winner: bigint;
        p1President: bigint;
        p2President: bigint;
        board1: string;
        board2: string;
        createdAt: bigint;
        finalizedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBoards"
  ): TypedContractMethod<
    [gameId: BytesLike],
    [[string, string] & { board1: string; board2: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGame"
  ): TypedContractMethod<
    [gameId: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        phase: bigint;
        winner: bigint;
        p1President: bigint;
        p2President: bigint;
        createdAt: bigint;
        finalizedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "operator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "presidentsSelected"
  ): TypedContractMethod<
    [gameId: BytesLike, p1President: BigNumberish, p2President: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shipsPlaced"
  ): TypedContractMethod<
    [gameId: BytesLike, playerNum: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shotFired"
  ): TypedContractMethod<
    [
      gameId: BytesLike,
      playerNum: BigNumberish,
      row: BigNumberish,
      col: BigNumberish,
      result: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "GameCreated"
  ): TypedContractEvent<
    GameCreatedEvent.InputTuple,
    GameCreatedEvent.OutputTuple,
    GameCreatedEvent.OutputObject
  >;
  getEvent(
    key: "GameFinalized"
  ): TypedContractEvent<
    GameFinalizedEvent.InputTuple,
    GameFinalizedEvent.OutputTuple,
    GameFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "PresidentsSelected"
  ): TypedContractEvent<
    PresidentsSelectedEvent.InputTuple,
    PresidentsSelectedEvent.OutputTuple,
    PresidentsSelectedEvent.OutputObject
  >;
  getEvent(
    key: "ShipsPlaced"
  ): TypedContractEvent<
    ShipsPlacedEvent.InputTuple,
    ShipsPlacedEvent.OutputTuple,
    ShipsPlacedEvent.OutputObject
  >;
  getEvent(
    key: "ShotFired"
  ): TypedContractEvent<
    ShotFiredEvent.InputTuple,
    ShotFiredEvent.OutputTuple,
    ShotFiredEvent.OutputObject
  >;

  filters: {
    "GameCreated(bytes32,uint256)": TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;
    GameCreated: TypedContractEvent<
      GameCreatedEvent.InputTuple,
      GameCreatedEvent.OutputTuple,
      GameCreatedEvent.OutputObject
    >;

    "GameFinalized(bytes32,uint8,bytes,bytes,uint256)": TypedContractEvent<
      GameFinalizedEvent.InputTuple,
      GameFinalizedEvent.OutputTuple,
      GameFinalizedEvent.OutputObject
    >;
    GameFinalized: TypedContractEvent<
      GameFinalizedEvent.InputTuple,
      GameFinalizedEvent.OutputTuple,
      GameFinalizedEvent.OutputObject
    >;

    "PresidentsSelected(bytes32,uint8,uint8)": TypedContractEvent<
      PresidentsSelectedEvent.InputTuple,
      PresidentsSelectedEvent.OutputTuple,
      PresidentsSelectedEvent.OutputObject
    >;
    PresidentsSelected: TypedContractEvent<
      PresidentsSelectedEvent.InputTuple,
      PresidentsSelectedEvent.OutputTuple,
      PresidentsSelectedEvent.OutputObject
    >;

    "ShipsPlaced(bytes32,uint8)": TypedContractEvent<
      ShipsPlacedEvent.InputTuple,
      ShipsPlacedEvent.OutputTuple,
      ShipsPlacedEvent.OutputObject
    >;
    ShipsPlaced: TypedContractEvent<
      ShipsPlacedEvent.InputTuple,
      ShipsPlacedEvent.OutputTuple,
      ShipsPlacedEvent.OutputObject
    >;

    "ShotFired(bytes32,uint8,uint8,uint8,uint8)": TypedContractEvent<
      ShotFiredEvent.InputTuple,
      ShotFiredEvent.OutputTuple,
      ShotFiredEvent.OutputObject
    >;
    ShotFired: TypedContractEvent<
      ShotFiredEvent.InputTuple,
      ShotFiredEvent.OutputTuple,
      ShotFiredEvent.OutputObject
    >;
  };
}
