/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BattleShip } from "./BattleShip";
export * as factories from "./factories";
export { BattleShip__factory } from "./factories/BattleShip__factory";
